/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.plu.cs.views;

import edu.plu.cs.controllers.ServerController;

/**
 *
 * @author Timothy Ernst
 */
public class ServerView extends javax.swing.JFrame {
    
    private final ServerController controller;
  
    /**
     * CONSTRUCTOR
     * Creates new form ServerView
     * @param serverControl the controller for this view
     */
    public ServerView(ServerController serverControl, String ip) {
        this.controller = serverControl;
        initComponents();
        addressTF.setText(ip);
    }
    
    /**
     * RELAY MESSAGE
     * Relays a message from server by appending serverFeedbackTA
     * @param msg the message to be relayed
     */
    public void serverFeedback(String msg){
        serverFeebackTA.append(msg + "\n");
    }
    
    /**
     * RELAY MESSAGE
     * Relays a message from server by appending serverFeedbackTA
     * @param msg the message to be relayed
     */
    public void userConnectionFeedback(String msg){
        clientFeedbackTA.append(msg + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverMessageTA = new javax.swing.JScrollPane();
        serverFeebackTA = new javax.swing.JTextArea();
        serverFeedbackLabel = new javax.swing.JLabel();
        serverInfoLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        portTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        clientInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientFeedbackTA = new javax.swing.JTextArea();
        shutDownButton = new javax.swing.JButton();
        serverTitleLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        clientFeedbackLabel = new javax.swing.JLabel();
        newClientWindowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serverFeebackTA.setEditable(false);
        serverFeebackTA.setColumns(20);
        serverFeebackTA.setFont(new java.awt.Font("Lucida Console", 0, 10)); // NOI18N
        serverFeebackTA.setLineWrap(true);
        serverFeebackTA.setRows(5);
        serverFeebackTA.setWrapStyleWord(true);
        serverMessageTA.setViewportView(serverFeebackTA);

        serverFeedbackLabel.setFont(new java.awt.Font("FangSong", 0, 18)); // NOI18N
        serverFeedbackLabel.setText("ServerConnection Feedback:");

        serverInfoLabel.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        serverInfoLabel.setText("Server Information");

        portLabel.setFont(new java.awt.Font("FangSong", 0, 18)); // NOI18N
        portLabel.setText("Port Number:");

        addressTF.setEditable(false);
        addressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTFActionPerformed(evt);
            }
        });

        portTF.setToolTipText("");

        jButton1.setText("Setup ServerConnection");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildServerButton(evt);
            }
        });

        clientInfoLabel.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        clientInfoLabel.setText("UserConnection Information");

        clientFeedbackTA.setEditable(false);
        clientFeedbackTA.setColumns(20);
        clientFeedbackTA.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        clientFeedbackTA.setLineWrap(true);
        clientFeedbackTA.setRows(5);
        clientFeedbackTA.setWrapStyleWord(true);
        jScrollPane1.setViewportView(clientFeedbackTA);

        shutDownButton.setText("Shut Down ServerConnection");
        shutDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutDownButtonActionPerformed(evt);
            }
        });

        serverTitleLabel.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 40)); // NOI18N
        serverTitleLabel.setText("S e r v e r  M a i n  F r a m e");

        addressLabel.setFont(new java.awt.Font("FangSong", 0, 18)); // NOI18N
        addressLabel.setText("IP Address:");

        clientFeedbackLabel.setFont(new java.awt.Font("FangSong", 0, 18)); // NOI18N
        clientFeedbackLabel.setText("UserConnection Feedback:");

        newClientWindowButton.setText("Generate New Client Window");
        newClientWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newClientWindowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(portLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(portTF))
                                .addComponent(shutDownButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(serverMessageTA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(serverInfoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(serverFeedbackLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(clientInfoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clientFeedbackLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(newClientWindowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(serverTitleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(serverTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverInfoLabel)
                    .addComponent(clientInfoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel)
                    .addComponent(newClientWindowButton))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(portTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shutDownButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(serverFeedbackLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serverMessageTA, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(clientFeedbackLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTFActionPerformed

    private void buildServerButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildServerButton
        int portNum = Integer.parseInt(portTF.getText());
        controller.setupServerConnection(portNum);
        portTF.setEditable(false);
    }//GEN-LAST:event_buildServerButton

    private void shutDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutDownButtonActionPerformed
        portTF.setText(null);
        portTF.setEditable(true);
        controller.stopServerConnection();
        serverFeebackTA.setText("Server has been terminated. Ready to generate new server");
    }//GEN-LAST:event_shutDownButtonActionPerformed

    private void newClientWindowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newClientWindowButtonActionPerformed
        controller.generateNewClientView();
        userConnectionFeedback("ClientView has been created.");
    }//GEN-LAST:event_newClientWindowButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTF;
    private javax.swing.JLabel clientFeedbackLabel;
    private javax.swing.JTextArea clientFeedbackTA;
    private javax.swing.JLabel clientInfoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newClientWindowButton;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTF;
    private javax.swing.JTextArea serverFeebackTA;
    private javax.swing.JLabel serverFeedbackLabel;
    private javax.swing.JLabel serverInfoLabel;
    private javax.swing.JScrollPane serverMessageTA;
    private javax.swing.JLabel serverTitleLabel;
    private javax.swing.JButton shutDownButton;
    // End of variables declaration//GEN-END:variables


}
